name: LineageOS_Tracker
on:
  # Should make sure it runs regularly
  schedule:
    - cron: '*/15 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  track0:
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: LOS

      - name: Run main.py
        run: sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} repos.txt

      - name: Commit and Push
        if: ${{ always() }}
        run: sudo bash git_commit.sh

  track1:
    if: always()
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: LOS

      - name: Run main.py
        run: sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} repos1.txt

      - name: Commit and Push
        if: ${{ always() }}
        run: sudo bash git_commit.sh

  track2:
    if: always()
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: LOS

      - name: Run main.py
        run: sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} repos2.txt

      - name: Commit and Push
        if: ${{ always() }}
        run: sudo bash git_commit.sh

  track3:
    if: always()
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: LOS

      - name: Run main.py
        run: sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} repos3.txt

      - name: Commit and Push
        if: ${{ always() }}
        run: sudo bash git_commit.sh

  track4:
    if: always()
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BOT_API: ${{ secrets.BOT_API }}
      CHAT_ID: ${{ secrets.CHAT }}
    # BOT_ID and CHAT_ID are used to communicate with Telegram API
    steps:
      - name: Install Dep
        run: sudo pip install pyTelegramBotAPI

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: LOS

      - name: Run main.py
        run: sudo python3 main.py ${{ secrets.CHAT }} ${{ secrets.BOT_API }} repos4.txt

      - name: Commit and Push
        if: ${{ always() }}
        run: sudo bash git_commit.sh
