# This is a basic workflow to help you get started with Actions

name: Update List
on:
  push:
    # Only update if these files are changed
    paths:
      - 'update.py'
      - 'repos.txt'
      - 'git_update_list.sh'
      - 'repos1.txt'
      - 'repos2.txt'
      - 'repos3.txt'
      - 'repos4.txt'

  # Enables us to manually run it
  workflow_dispatch:

jobs:
  # This workflow contains a single job called track
  track:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          repository: geek0609/LineageOS-Tracker
          token: ${{ secrets.PAT }}
          ref: LOS

      - name: Update List
        run: ls && sudo python3 update.py

      - name: Commit and Push Changes
        run: sudo bash git_update_list.sh
